### ISSUE TITLE
Cluster模式创建不了容器

### ISSUE THREAD

**Issue by guoai2015** [humpback/humpback#12]
全部都是按照教程安装的，私有仓库里面也上传了镜像。就是创建容器的时候报错。组删除了重新创建都不行。

错误内容：

{"Code":-1002,"Error":"request failure error","Contnet":"cluster group not found","ResponseID":"61770f83-c011-4037-9137-17b7d01ee5bd","Data":null}

**Comment by rl5c** [comment]
从现象上看，humpback-center服务在启动时会调用humpback-web的后端API同步一次分组数据，但这个同步过程在humpback-center的初始化过程中，没有retry，如果先启动humpback-center，后启动humpback-web，会有无法抓取集群分组信息的风险，导致humpback-center中无分组信息。

**Comment by guoai2015** [comment]
感谢回复，看了humpback-center的日志，发现连不上humpback-web，我启动容器的时候用了桥接模式，映射端口到宿主机上的，结果容器内部访问不到宿主机的端口。这种情况非得用host模式吗？

**Comment by rl5c** [comment]
关于bridge与host模式，只是容器网络的隔离，但从运行机制来说，与humpback-center无太大关系，可能还是要检查本地系统是否有限制或防火墙端口限制等因素；humpback-center两种网络模式都可以，运行时确保需要映射的Volumes正确即可。 不过我一般都使用host模式。一般做Cluster启动应用相关的容器+服务发现才使用bridge+auto port.

**Comment by station19** [comment]
作者应该提供一份 docker-compose.yml 一次搞定

**Comment by rl5c** [comment]
我会做一个docker-compose一步安装到位，感谢建议！
