### ISSUE TITLE
升级容器时，无法输入大于10位的标签

### ISSUE THREAD

**Issue by hstarorg** [humpback/humpback#13]
有些镜像的标签会超过10位，导致无法在新标签中输入。
![image](https://user-images.githubusercontent.com/4043284/33239853-101672ec-d2e6-11e7-8e2e-437177c46830.png)

重现版本： humpback-web: 1.0.1

**Comment by hstarorg** [comment]
Why close my issue?

**Comment by winifredTomlinson** [comment]
问题已解决

**Comment by hstarorg** [comment]
Okay, please add some remark text when close issue.
