### ISSUE TITLE
add default value of --log-opt on docker run

### ISSUE THREAD

**Issue by aames0130** [humpback/humpback#14]
docker 預設會將  container 的 console 輸出成檔案，
這會吃宿主機的 Hard disk，
假如沒有限制大小，服務一直跑，最後宿主機的 Hard disk會被吃光光，
服務也就掛了。
這可以透過 docker run --log-opt max-size=10m --log-opt max-file=3
來限制container 的 console 產生的 log 大小與數量，
但是目前 Humpback 並不支持參數 --log-opt 的輸入，
建議支持，或是加入預設值，避免因為 log 的因素將宿主機弄掛。

**Comment by rl5c** [comment]
提议很好，我改改！

**Comment by winifredTomlinson** [comment]
对Single 模式下创建、克隆container和Cluster模式下创建、克隆container新增Log Config属性

![log-config](https://user-images.githubusercontent.com/15845594/38722512-b956a6a4-3f30-11e8-9a0d-13b4e8d875fb.png)

PS：
Single模式创建container时Log Config Driver的默认值为当前目标服务器的--log-driver值，且该值不能被修改，若该值为'json-file'，则--log-opt的值默认为max-size=10m、max-file=3
Single模式克隆container时，Log Config的值与被克隆container的Log Config一致

Cluster模式创建container时Log Config Driver的默认值为'json-file'，Opts默认值为max-size=10m、max-file=3
Cluster模式克隆container时Log Config表现与Single模式一致
