### ISSUE TITLE
pull 时超时失败

### ISSUE THREAD

**Issue by zsz00** [humpback/humpback#17]
docker run -d -ti --net=host --restart=always -e DOCKER_API_VERSION=v1.35 -v /var/run/:/var/run/:rw --name=humpback-agent humpbacks/humpback-agent:1.0.0

docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/72/7213b981d7d9943a3ff9199f5a5bbbf0959d1aff16d87184f339a337940e8d9b/data?Expires=1523666488&Signature=WdYXwwgJNPDPTGa1~VZ-VnKxjNiMNMTs6WHJ1tgT3UpfOZpD674u1UG08TBBWiqrY-IQ3Y-aU1F2cZzyd4IxDeYmuOE0n2RRdB9P0HlWxryDs9M2SX9IHxTI5NZoXTjMrrDhpQZE~IGIApqB~e~EXjgf2nNcJo4aMHcH2FgllrQ_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.

怎么办?

**Comment by hstarorg** [comment]
Maybe you should check your network or use `ss`

**Comment by rl5c** [comment]
Please check you network.
`1.0.0` Version is too old, pull latest version is `1.3.0`.
```bash
$ docker pull humpbacks/humpback-web:1.3.0
$ docker pull humpbacks/humpback-agent:1.3.0
$ docker pull humpbacks/humpback-center:1.3.0
```
