### ISSUE TITLE
Docker的API已经更新至API version:1.37,是否支持

### ISSUE THREAD

**Issue by songjave** [humpback/humpback#18]
docker最新版已经将API更新到了1.37，不知道Humpback Agent的API是否应该填写为1.37还是继续使用原来的1.21啊

**Comment by hstarorg** [comment]
填写最新的1.37

**Comment by rl5c** [comment]
最新镜像版本为：1.3.0，已采用docker官方最新开发包编译，在兼容性上应该支持……
