### ISSUE TITLE
humpback get images failed

### ISSUE THREAD

**Issue by zhhp1314520** [humpback/humpback#20]
点击Hub报“get images failed”，请帮忙看看什么问题。
registry单独使用是ok，也在System Config中配置了Enabel Private Registry

**Comment by rl5c** [comment]
浏览器点击hub前，先按F12看看network中报了什么错，发出来看看。
另外参照一下，检查一下自己的仓库配置开通跨域访问没有，因为humpback-web是浏览器直接访问私仓，仓库的跨域配置必须打开：https://github.com/hstarorg/HstarDoc/blob/master/%E8%BF%90%E7%BB%B4%26%E9%83%A8%E7%BD%B2/Docker%E5%AE%B9%E5%99%A8%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0Humpback%E8%BF%9B%E9%98%B6-%E7%A7%81%E6%9C%89%E4%BB%93%E5%BA%93.md

**Comment by AnInputForce** [comment]
你好，遵从上述配置，我解决了hub报错的问题。但是别的菜单 碰上了类似的问题，麻烦帮忙看看。
点击 Server Overview 127.0.0.1 ，Containers 可以列出本机上的容器
但是点击  Docker Images ，就弹出 “get images failed”。
network报错:WebSocket network error: The operation couldn’t be completed. Connection refused

本地环境：macbook，docker-ce .
没有配置 host模式，貌似mac不支持；
我的启动命令如下：
`docker run -d -p 5000:5000 --restart=always -v /usr/local/opt/app/registry-var/:/var/lib/registry/ registry`

**Comment by hstarorg** [comment]
@lon-yang 建议把humpback-web更新为产线包（BTW：当前是dev包）

**Comment by rl5c** [comment]
@AnInputForce 
你好！左侧点击服务器地址后，会进入所选服务器的容器和镜像管理界面，分别显示`Containers`和`Docker Images`两个Tab页，这已经和访问仓库无关了，当点击`Containers`或`Docker Images`时，都是访问`humpback-agent`这个服务，你可以直接访问：http://{humpback-agent主机地址}:8500/v1/images,看能否列出镜像列表，若不能访问，请确认一下humpback-agent的版本号，会humpback-web的版本号，我们好排查一下。访问时可以借助restful client工具检查一下报错的详细信息。
