### ISSUE TITLE
集群搭建怎么不显示菜单

### ISSUE THREAD

**Issue by zxxtyj** [humpback/humpback#21]
我的Groups里怎么没有子菜单Single和Cluster。三个组件都装好了。我的humpback-center中心这样启动的
docker run -d -ti --net=host --restart=always \
 --name=humpback-center \
 -e HUMPBACK_SITEAPI=http://10.0.3.56:8000/api \
 -e CENTER_LISTEN_PORT=:8589 \
 -e CENTER_API_ENABLECORS=true \
 -e DOCKER_CLUSTER_URIS=zk://10.0.3.56:2181,10.0.3.57:2181 \
 -e DOCKER_CLUSTER_NAME=humpback/center \
 -v /data/humpback-center/cache:/opt/humpback-center/cache \
 -v /data/humpback-center/logs:/opt/humpback-center/logs \
 humpbacks/humpback-center:1.3.0

**Comment by hstarorg** [comment]
请看SystemConfig中，启用集群模式。
![image](https://user-images.githubusercontent.com/4043284/40770089-4d8dca74-64ec-11e8-96d9-9f550f1022f4.png)

**Comment by zxxtyj** [comment]
{"Code":-1002,"Error":"request failure error","Contnet":"cluster group not found","ResponseID":"7f4dbbc2-7aa2-46b6-b478-94a711570626","Data":null}
我的System Config 配置是这样的 ：
http://10.0.3.56:8589  对吗
在创建容器的时候报的如上的错误

**Comment by rl5c** [comment]
@zxxtyj 
你好，从错误描述上看，这个问题是这样导致的：
humpback-center是一个容器调度器，在启动时需要到humpback-web抓取分组信息，而humpback-center比humpback-web先启动，当访问humpback-web站点时，在group里创建了分组，此时集群模式选项没有在system config中勾选打开，会导致humpback-web不会同步分组信息到humpback-center，导致humpback-center内存中无分组信息，所以出现：cluster group not found。
你可以将humpback-center重启一次，它会立即到站点同步一次分组数据。

**Comment by rl5c** [comment]
@zxxtyj 
若还是不能解决，请查看如下链接，检查humpback-center的日志，排查是不是humpback-center无法访问humpback-web的API，导致无法抓取分组数据信息。
[https://github.com/humpback/humpback/issues/12]https://github.com/humpback/humpback/issues/12
