### ISSUE TITLE
集群模式下，容器怎么部署到其他节点

### ISSUE THREAD

**Issue by YuxuanSu-Sean** [humpback/humpback#23]
使用集群模式部署容器，没有提供指定节点选项的话，是指容器会自动调度到其他节点吗？
但是我部署了好几个容器，都跑主节点上去了，没有实现负载均衡，是否哪边配置需要注意？
另外再请教一个小白问题，single模式切换到cluster模式后，原节点上部署的容器是不被发现的吗？
![image](https://user-images.githubusercontent.com/37233197/41883128-5b0fc3f4-791f-11e8-85ed-b2c90a6571a5.png)

**Comment by rl5c** [comment]
你好！这个问题需要看看humpback-center的日志，调度器的分配原则是按实例数均分，若实例数大于节点数，会先均分一次，剩下的实例再选择容器较少或内存较大的节点, 根据我的判断，可能你的情况应该在于调度器已经尝试分布到其它节点了，但在那些节点创建失败了，所以在retry时最终选择了主节点。创建失败的情况有多种，详细错误全都记录在humoback-center的日志里，所有需要我可以配合你排查。同时再看看未分配的节点的humpback-agent容器日志，是不是加入集群失败导致，必要时qq:52882785
