### ISSUE TITLE
Chrome浏览器控制台报错：WebSocket 错误

### ISSUE THREAD

**Issue by SunPan92** [humpback/humpback#24]
使用谷歌浏览器，在Ubuntu虚拟机上搭建的docker，但是浏览器F12控制台报错：WebSocket connection to 'ws://localhost:9107/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED。其他功能正常，没有发现使用有问题的地方，就是控制台报这个错误。
版本humpback-web:1.3.0，humpback-agent:1.3.2，registry：2.5.2

**Comment by hstarorg** [comment]
这是由于这个镜像是DEV镜像，所以对本地环境有一点依赖。对使用无影响（由于是DEV包，所以JS文件会比较大些）。

**Comment by rl5c** [comment]
我们在下次发布镜像时会对环境依赖做一些调整。
