### ISSUE TITLE
同一个组里的容器直接如何互相访问？

### ISSUE THREAD

**Issue by rushairer** [humpback/humpback#4]
同一个组里的容器直接如何互相访问？网络应该如何设？

如果是web服务，外网该如何访问？ 自己做负载均衡的话，IP如何确定？

谢谢

**Comment by hstarorg** [comment]
一般采用HTTP或者RPC进行通信。ip是你容器部署的那台机器IP。

**Comment by instance-oom** [comment]
互相访问的话有两种方式，第一种使用 Link，第二种是常规方法使用 IP + Port

**Comment by rushairer** [comment]
多谢回复。
如果是集群，在创建容器的时候就不能用Link了。
因为会涉及到自动伸缩，所以绑定IP和Port也不稳妥啊？
希望加上类似k8s的service那样的功能。
如果是直接端口服务的web服务，我有3台机器，但是自动伸缩的话，应该是可以大于3台机器的。那容器的公开端口就不能写死，是随机的。这就需要前层再有个负载均衡的服务。

**Comment by hstarorg** [comment]
我们这边是结合gateway做自动负载均衡（容器产生调用，自动更新gateway），保证对外提供的api提供是一致的。

**Comment by rushairer** [comment]
gateway是内部的项目？

**Comment by hstarorg** [comment]
就是api网关，在humpback中，容器发生变化之后，会有一个WebHooks，利用这个就可以将变化后的数据更新到网关中（或者其他地方），这样也就达到了自动伸缩，api接口不变化的效果。

**Comment by rushairer** [comment]
多谢，我大概懂了。
比如我现在启动了5个helloworld的容器
可以通过API
http://172.16.1.171:8589/v1/groups/cdb90e1c-e95c-4529-985c-a4c27844fa36/collections
获得所有运行helloworld的容器的IP和PublicPort
然后只需要自己写个网关服务就可以了？
另外通过WebHooks来刷新网关配置。
是这样吗？

再次感谢！

**Comment by rushairer** [comment]
我在集群里架了skydns。是不是需要自己把每个容器注册到dns啊？

**Comment by hstarorg** [comment]
@rushairer 是这个意思。一个入口访问，至于内部反向代理到哪儿，调用者才不关心，通过WebHooks自动更新即可。

对于这个dns，和gateway类似，通过webHooks刷新dns配置就是了。（skydns没有使用过，但思路应该是相通的）

**Comment by rushairer** [comment]
可以把zookeeper缓存etcd的吧？
k8s用的skydns，通过etcd刷新dns信息。
建议后续把网关功能也加上，这样humpback就可以提供完整的服务给中小型团队使用了，这样更利于项目的成长和社区的壮大。

**Comment by hstarorg** [comment]
是可以换成etcd的。
至于gateway，这个和humpback本身并没有关系。所以可能不会加这块功能。这又是一大套东西，我们尽量保持humpback纯粹。

**Comment by hstarorg** [comment]
问题已完毕，关闭issue
