### ISSUE TITLE
请问webhook该怎么用？

### ISSUE THREAD

**Issue by rushairer** [humpback/humpback#5]
我没有找到具体的使用文档，求助。

**Comment by rl5c** [comment]
https://humpback.github.io/humpback/#/zh-cn/cluster-container-schedule?id=%e5%85%b3%e4%ba%8ewebhook

**Comment by rushairer** [comment]
我写了个php程序接收hook的数据，可是get post过来的内容都是空的啊

**Comment by rl5c** [comment]
看看center目录下的logs目录，日志里带“[#cluster#] webhook” 的地方，检查POST成功没有。

**Comment by rushairer** [comment]
原来是post的raw格式的json

用file_get_contents('php://input')就收到了

多谢

**Comment by rl5c** [comment]
不谢！你是想通过php来更新DNS吗？我们没有提供网关，主要是考虑gateway的定制化太强，所以由自己来处理。每次WebHooks触发，会反映出最新的容器分配信息。

**Comment by rushairer** [comment]
是的。每次容器变化的时候，通过php来刷新DNS。
然后用 etcd+confd+nginx做网关

**Comment by rushairer** [comment]
每个容器的eth0的IP怎样获得呢？

我这里都是 0.0.0.0
```
Ports": [
          {
            "PrivatePort": 80,
            "PublicPort": 32778,
            "Type": "tcp",
            "Ip": "0.0.0.0"
          }
        ]
```

**Comment by rushairer** [comment]
呃，找到方法了。略微复杂。
先确定容器的宿主机IP然后
用 http://IP:8500/dockerapi/v2/containers/`{containerID}`
😂

**Comment by hstarorg** [comment]
处理完毕，关闭
